name: Test Github Actions

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display all files
      run: |
        ls -la